# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 607)
        Form.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        Form.setWindowOpacity(1.0)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-60, 0, 901, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/bg.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(470, 0, 371, 611))
        self.label_2.setStyleSheet("background-color: rgba(240, 240, 240,100);")
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(510, 60, 281, 101))
        self.label_3.setStyleSheet("border: 2px solid rgba(155, 155,155, 0.5)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(510, 180, 281, 101))
        self.label_4.setStyleSheet("border: 2px solid rgba(155, 155,155, 0.5)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(510, 70, 81, 71))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("images/temp.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(520, 200, 61, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/humi.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.temp_value = QtWidgets.QLabel(Form)
        self.temp_value.setGeometry(QtCore.QRect(590, 90, 151, 51))
        self.temp_value.setStyleSheet("font: 20pt \"Arial Narrow\";")
        self.temp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_value.setObjectName("temp_value")
        self.humi_value = QtWidgets.QLabel(Form)
        self.humi_value.setGeometry(QtCore.QRect(590, 210, 151, 51))
        self.humi_value.setStyleSheet("font: 20pt \"Arial Narrow\";")
        self.humi_value.setAlignment(QtCore.Qt.AlignCenter)
        self.humi_value.setObjectName("humi_value")
        self.light = QtWidgets.QLabel(Form)
        self.light.setGeometry(QtCore.QRect(600, 330, 91, 81))
        self.light.setText("")
        self.light.setPixmap(QtGui.QPixmap("images/lampoff.png"))
        self.light.setScaledContents(True)
        self.light.setObjectName("light")
        self.people = QtWidgets.QLabel(Form)
        self.people.setGeometry(QtCore.QRect(80, 330, 281, 261))
        self.people.setText("")
        self.people.setPixmap(QtGui.QPixmap("images/people_gray.png"))
        self.people.setScaledContents(True)
        self.people.setObjectName("people")
        self.chart = QtWidgets.QLabel(Form)
        self.chart.setGeometry(QtCore.QRect(40, 30, 390, 280))
        self.chart.setText("")
        self.chart.setPixmap(QtGui.QPixmap("images/折线图占位.png"))
        self.chart.setScaledContents(True)
        self.chart.setObjectName("chart")
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(610, 410, 75, 41))
        self.button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/switch_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button.setIcon(icon)
        self.button.setIconSize(QtCore.QSize(50, 50))
        self.button.setFlat(True)
        self.button.setObjectName("button")

        self.retranslateUi(Form)
        self.button.clicked.connect(self.light.update)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "环境监控"))
        self.temp_value.setText(_translate("Form", "55℃"))
        self.humi_value.setText(_translate("Form", "60rh"))
